# Generated by Django 5.2.4 on 2025-08-04 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("issues", "0002_issue_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="issue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.issue",
            ),
            preserve_default=False,
        ),
    ]
