# Generated by Django 5.0.14 on 2025-08-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_issue_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="cover",
            field=models.ImageField(
                default="/media/images/placeholder.png", upload_to="images/"
            ),
            preserve_default=False,
        ),
    ]
