# Generated by Django 5.2.4 on 2025-07-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("WRITER", "Writer"), ("EDITOR", "Editor")],
                default="WRITER",
                max_length=255,
            ),
        ),
    ]
